yolo_model:

  config_file:
    name: yolov3_TSR.cfg
  weight_file:
    name: yolov3_TSR_113344.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
